### PR TITLE
Reduce image size and introduce Alpine variant

### PR DESCRIPTION
**Pull request by teohhanhui**

### CODE REVIEW

**Comment by teohhanhui** [comment]
The alpine variant of Varnish 6.0 does not work properly. But it's the same with the official `varnish` (6.0) package from alpine 3.8, reproducible here: https://github.com/teohhanhui/api-platform/tree/alpine-varnish-crash

**Comment by jewome62** [comment]
Currently, yes that not work from you PR
```
jewome62@jewome62-tilleuls:~/projects/nord-compo/paprika$ docker logs paprika_cache-proxy_1
Debug: Platform: Linux,4.13.0-45-generic,x86_64,-junix,-smalloc,-sdefault,-hcritbit
Debug: Child (17) Started
Error: Child (17) not responding to CLI, killed it.
Error: Child (17) Pushing vcls failed:
CLI communication error (hdr)
Debug: Stopping Child
Error: Child (17) died signal=11 (core dumped)
CLI result = 400
Info: Child (17) said Child starts
Debug: Child cleanup complete

```

**Comment by jewome62** [comment]
Same from your fork on api-platform
```
Debug: Platform: Linux,4.13.0-45-generic,x86_64,-junix,-smalloc,-sdefault,-hcritbit
Debug: Child (18) Started
CLI result = 400
Error: Child (18) not responding to CLI, killed it.
Error: Child (18) Pushing vcls failed:
CLI communication error (hdr)
Debug: Stopping Child
Error: Child (18) died signal=11 (core dumped)
Info: Child (18) said Child starts
Debug: Child cleanup complete

```

**Comment by teohhanhui** [comment]
I've opened https://bugs.alpinelinux.org/issues/9094

**Comment by teohhanhui** [comment]
And Varnish 6.0 is fixed on Alpine! :tada:

**Comment by teohhanhui** [comment]
## Varnish 6.0 image sizes

### Before

Debian Stretch: 256 MB

### After

Debian Stretch: 168 MB
Alpine 3.8: 114 MB

**Pull request merged**
